### PR TITLE
add footer with version to all pages

### PR DESCRIPTION
**Pull request by HParker**
screen shot 2015-12-01 at 11 35 57 pm

Added a footer as per issue #17 

I think it looks nice and it should always have the right version number and stay at the bottom of the page. Let me know if you have any ideas/improvements.

### CODE REVIEW

**Comment by mrnugget** [comment]
Nice! Thanks a lot for this!

Two questions:
* The footer is sticky, right? It's always going to stick to the bottom. That's the reason for the wrapper (`<div id="wrap">`), correct?
* Do you think it would be better to have the `Applikatoni X.X.X` and the copyright notice on two separate lines? I'm still not sure.

**Comment by HParker** [comment]
Thanks for the response,

> The footer is sticky, right? It's always going to stick to the bottom. That's the reason for the wrapper `(<div id="wrap">)`, correct?

yes, I wish there was a better way of getting a sticky footer, but this is the common way to add a footer currently. One thing to note is the footer does move over the content when you scroll up, which is somewhat typical, but can be changed if it is an issue.

applikatoni-sticky-footer


> Do you think it would be better to have the Applikatoni X.X.X and the copyright notice on two separate lines? I'm still not sure.

This is what it looks like with the footer on two lines:
screen shot 2015-12-02 at 10 01 38 am

Do you like that better? the reason I didn't go with it is because the © doesn't line up with the `A` in Applikatoni above. That is solvable, but I didn't want to get into it here. easy solution would be two lines centered at the bottom of the page instead of off to the side.

**Comment by Wind0r** [comment]
Well done :)
But i really would like it if it is not a sticky Footer, it is "stealing" space under the application tab.
I would like it at the end of the page and if the page do not have that much contend on the bottom of the window.
 Like Github and a lot of other Sites do it.

**Comment by fabrik42** [comment]
I think it's a good idea but we can achieve this with bootstrap (which we already include). No need for the extra wrapper div. 

http://getbootstrap.com/examples/sticky-footer-navbar/

**Comment by HParker** [comment]
sorry I didn't mean to trigger CI 3 times!

Anyway, Thanks for the feedback! I agree this looks much better. (the gif seems to have lost the color on some frames, but the footer is still light grey like the header)
applikatoni-sticky-footer2

**Comment by HParker** [comment]
*Question:* Is there a test I could add for the change to the request handler? We return the version with every request now, but the tests don't know, but it is a constant and I wouldn't test the constant on its own, so I am unsure.

**Comment by mrnugget** [comment]
> But i really would like it if it is not a sticky Footer, it is "stealing" space under the application tab.
> I would like it at the end of the page and if the page do not have that much contend on the bottom of the window.

Yep! I like that!

> Question: Is there a test I could add for the change to the request handler? We return the version with every request now, but the tests don't know, but it is a constant and I wouldn't test the constant on its own, so I am unsure.

No, I don't think it's worth the trouble to add a test for the layout (at least at the moment).

**Comment by mrnugget** [comment]
I just checked this out locally. Perfect! Thanks a lot! :+1:

**Pull request merged**
