### PR TITLE
Fix issue #10

### PR DESCRIPTION
**Pull request by flakyfilibuster**
Firefox does not support break-word.
Switched to word-break: break-all

### CODE REVIEW

**Comment by mrnugget** [comment]
Nice! Two things:

1. Add yourself to the CHANGELOG :)
2. Something wrong with your git configuration? The commit author/committer doesn't match your GitHub username. I don't know if that is by accident or on purpose.

**Comment by Wind0r** [comment]
As written under the issue. I do not think 'break-all'  is the right solution cause it formats a lot of comments not that nice.
I would "prefere" some fallback for firefox that do not break the working break-word in other browsers.

At least we should do:
```
.deployment-comment {
  word-break: break-all;
  word-break: break-word;
}
```
So Firefox will use break-all. Since it ignores break-word cause it do now know it. 
And ever browser that supports break-word will do break-word

I got this commit ready on my local branch yesterday but searched for a better solution.

**Comment by flakyfilibuster** [comment]
Meop, sorry, totally missed that part - my bad.

Well if you have it fixed in your branch anyways, no need for me to make this pull request - let me concentrate on some other issue :)

Cheers

**Comment by mrnugget** [comment]
Back from vacation.... What's the status here?

And how does this compare to https://github.com/applikatoni/applikatoni/pull/16? Need your help here @flakyfilibuster and @Wind0r :)

**Comment by Wind0r** [comment]
This enable break-all on all browsers even those who support break-word.
#16 will use break-all only as a fallback. Since non Webkit browsers will ignore the break-word line.

**Comment by mrnugget** [comment]
Alright, thanks for clearing this up. I'll close this now and we'll concentrate on #16.

**Pull request closed without merging**
